# Generated by Django 4.1.1 on 2023-12-03 13:57

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField(verbose_name='Date of the event')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('edu', models.CharField(blank=True, default='', max_length=200)),
                ('field_of_expertise', models.CharField(max_length=200)),
                ('desg', models.CharField(max_length=200)),
                ('yoe', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='notes',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
