# Generated by Django 4.1.1 on 2023-12-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_event_faculty_course_notes_alter_course_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Announcement', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=models.CharField(max_length=5000),
        ),
    ]
