# Generated by Django 4.1.1 on 2023-12-03 14:14

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_event_title_alter_event_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
