# Generated by Django 4.1.1 on 2023-12-04 06:42

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_event_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='notes',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
