# Generated by Django 4.1.1 on 2023-12-04 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_course_content_alter_course_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_faculty',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.faculty'),
        ),
    ]
