# Generated by Django 4.1.1 on 2023-12-04 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_faculty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_faculty',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.faculty'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
