# Generated by Django 4.1.1 on 2023-12-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_course_course_faculty_alter_course_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
