# Generated by Django 4.1.1 on 2023-12-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_course_title_alter_faculty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
