# Generated by Django 4.1.1 on 2023-12-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_faculty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, unique=True),
        ),
    ]
