# Generated by Django 5.0.7 on 2025-04-18 19:06

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_faculty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
